// Markable — Module 04, IMPROVE.
//
// Nothing here is generated by a model. Every action is a detector's finding
// turned into a sentence with the finding's own numbers in it, and every one
// carries the scripts it came from so the faculty can check it rather than
// take it on trust.
//
// The rule this file follows: an action only exists if a detector reported
// something. When a detector found nothing, there is no action — Markable does
// not fill the page with advice it cannot support.

import type { Script, Criterion } from './types';
import {
  detectDrift,
  detectLengthEffect,
  findSimilarPairs,
  findCommonErrors,
  criterionPerformance,
} from './insights';

export type ActionArea = 'teaching' | 'assessment' | 'marking';

export interface Action {
  id: string;
  area: ActionArea;
  /** The observation, in the faculty's own numbers. */
  finding: string;
  /** What to actually do about it. One sentence, imperative. */
  suggestion: string;
  /** How many students or scripts sit behind it — shown as the weight. */
  weight: number;
  weightLabel: string;
  /** Where to go and check it. */
  href: string;
  hrefLabel: string;
}

const AREA_ORDER: Record<ActionArea, number> = { teaching: 0, assessment: 1, marking: 2 };

export const AREA_COPY: Record<ActionArea, { title: string; blurb: string }> = {
  teaching: {
    title: 'For your teaching',
    blurb: 'Specific steps a specific number of students missed. Each one is a few minutes of class time, not a syllabus change.',
  },
  assessment: {
    title: 'For the question',
    blurb: 'Where this question stopped telling you who understood the material. Worth reading before you set it again.',
  },
  marking: {
    title: 'For the next time you mark',
    blurb: 'What happened to your own marking while you did it, and the smallest thing that would change it.',
  },
};

export function buildActions(
  scripts: Script[],
  criteria: Criterion[],
  totalMarks: number
): Action[] {
  const out: Action[] = [];
  const n = scripts.length;

  // ------------------------------------------------------------- teaching
  for (const e of findCommonErrors(scripts)) {
    const share = Math.round((e.count / n) * 100);
    out.push({
      id: `teach-${e.tag}`,
      area: 'teaching',
      finding: `${e.count} of ${n} students (${share}%) lost marks for the same thing: ${e.label.toLowerCase()}.`,
      suggestion:
        e.count / n >= 0.5
          ? 'Re-teach this step to the whole class — at this share it is not a few students struggling, it is the class.'
          : 'Work one example through this step in class, and say out loud why it is the part people skip.',
      weight: e.count,
      weightLabel: `${e.count} students`,
      href: '/class',
      hrefLabel: 'See the scripts',
    });
  }

  // ----------------------------------------------------------- assessment
  for (const p of criterionPerformance(scripts, criteria)) {
    if (p.verdict === 'review-the-question') {
      out.push({
        id: `assess-${p.id}`,
        area: 'assessment',
        finding: `Of the ${p.strongN} students who earned full marks on every other part of this question, ${p.strongFailed} still missed "${p.label.toLowerCase()}".`,
        suggestion:
          'Review how this step is worded and whether it was ever explicitly required — when students who understand everything else still miss it, the step is not separating understanding from misunderstanding.',
        weight: p.strongFailed,
        weightLabel: `${p.strongFailed} of ${p.strongN} strong answers`,
        href: '/questions',
        hrefLabel: 'See the breakdown',
      });
    } else if (p.verdict === 'genuinely-hard') {
      out.push({
        id: `assess-${p.id}`,
        area: 'assessment',
        finding: `"${p.label}" was the hardest step — students earned ${Math.round(p.facility * 100)}% of its marks — but the strongest answers did get it.`,
        suggestion: 'Keep it. It is doing the job a hard question is supposed to do: telling the strongest answers apart from the rest.',
        weight: p.noCredit,
        weightLabel: `${p.noCredit} scored nothing here`,
        href: '/questions',
        hrefLabel: 'See the breakdown',
      });
    }
  }

  // -------------------------------------------------------------- marking
  const drift = detectDrift(scripts, totalMarks);
  if (drift.significant) {
    const later = scripts.filter((s) => s.order > drift.splitAt).length;
    out.push({
      id: 'mark-drift',
      area: 'marking',
      finding: `Partial-credit answers after script ${drift.splitAt} were marked ${drift.step.toFixed(2)} marks tighter than the ones before it (+${drift.earlyMean.toFixed(2)} against the guide, then +${drift.lateMean.toFixed(2)}).`,
      suggestion: `Re-read the partial-credit answers among the last ${later} scripts against the guide you approved, then decide whether the earlier marks or the later ones are the standard you want.`,
      weight: later,
      weightLabel: `${later} scripts after the shift`,
      href: '/you',
      hrefLabel: 'See the chart',
    });
  }

  const pairs = findSimilarPairs(scripts, 5);
  if (pairs.length) {
    out.push({
      id: 'mark-pairs',
      area: 'marking',
      finding: `${pairs.length} pairs of answers were credited identically against every criterion but marked ${Math.min(...pairs.map((p) => p.gap))}–${Math.max(...pairs.map((p) => p.gap))} marks apart.`,
      suggestion: 'Open the pairs and settle each one before results go out — these are the marks a student is most likely to appeal, and the ones hardest to defend from memory.',
      weight: pairs.length * 2,
      weightLabel: `${pairs.length * 2} scripts`,
      href: '/you',
      hrefLabel: 'Compare them',
    });
  }

  const len = detectLengthEffect(scripts, totalMarks);
  if (len.significant) {
    out.push({
      id: 'mark-length',
      area: 'marking',
      finding: `Among answers credited identically, those over ${len.threshold} words were marked ${len.advantage.toFixed(2)} marks higher.`,
      suggestion: 'Mark the criteria before you form an impression of the answer — length reads as confidence long before you notice it doing so.',
      weight: len.longN,
      weightLabel: `${len.longN} longer answers`,
      href: '/you',
      hrefLabel: 'See the check',
    });
  }

  return out.sort(
    (a, b) => AREA_ORDER[a.area] - AREA_ORDER[b.area] || b.weight - a.weight
  );
}
